platform :ios, '8.0'
target 'IPOAsk' do
 # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IPOAsk
	pod 'SDWebImage'
	pod 'Masonry'
	pod 'MJRefresh'
	pod 'Bugly'
    pod 'FMDB'
    pod 'QQ_XGPush'
end


